services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    hostname: app
    command: ["sleep", "infinity"]
    environment:
      HADOOP_HOME: /opt/hadoop
    volumes:
      - hadoop-home:/opt/hadoop
  namenode:
    image: apache/hadoop:3.3.6
    hostname: namenode
    command: ["hdfs", "namenode"]
    environment:
      ENSURE_NAMENODE_DIR: "/data/dfs/name" # hdfs-default.xml: dfs.namenode.name.dir
    env_file:
      - ./config
    ports:
      - 8020:8020 # rpc
      - 9870:9870 # http
    volumes:
      - hadoop-home:/opt/hadoop
  datanode:
    image: apache/hadoop:3.3.6
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
    ports:
      - 9864:9864 # http
      - 9866:9866 # transfer
      - 9867:9867 # ipc
volumes:
  hadoop-home:
